export const transactions = [
  {
    id: '1',
    category: 'Food',
    description: 'Lunch at restaurant',
    amount: '$20.00',
    isIncome: false,
    date: '22 May',
  },
  {
    id: '2',
    category: 'Salary',
    description: 'Monthly salary',
    amount: '$3,000.00',
    isIncome: true,
    date: '20 May',
  },
  {
    id: '3',
    category: 'Transport',
    description: 'Taxi ride',
    amount: '$15.00',
    isIncome: false,
    date: '19 May',
  },
  {
    id: '4',
    category: 'Freelance',
    description: 'Project payment',
    amount: '$500.00',
    isIncome: true,
    date: '18 May',
  },
  {
    id: '5',
    category: 'Shopping',
    description: 'New shoes',
    amount: '$80.00',
    isIncome: false,
    date: '17 May',
  },
  {
    id: '6',
    category: 'Utilities',
    description: 'Electricity bill',
    amount: '$60.00',
    isIncome: false,
    date: '16 May',
  },
  {
    id: '7',
    category: 'Investment',
    description: 'Stocks purchase',
    amount: '$200.00',
    isIncome: true,
    date: '15 May',
  },
  {
    id: '8',
    category: 'Entertainment',
    description: 'Movie tickets',
    amount: '$30.00',
    isIncome: false,
    date: '14 May',
  },
  {
    id: '9',
    category: 'Gift',
    description: 'Birthday gift for friend',
    amount: '$50.00',
    isIncome: false,
    date: '13 May',
  },
  {
    id: '10',
    category: 'Bonus',
    description: 'Year-end bonus',
    amount: '$1,000.00',
    isIncome: true,
    date: '12 May',
  },
];
